name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@main
        with:
          deno-version: "~1.37"
      - uses: actions/cache@v3
        with:
          path: ~/.cache/deno        # see https://deno.land/manual/linking_to_external_code
          key: ${{ runner.os }}-deno # it seems there's no particular cache keying required
          restore-keys: |
            ${{ runner.os }}-deno
      - name: deno info
        run: |
          deno --version
          deno info
      - name: lint
        run: |
          deno lint
      - name: fmt
        run: |
          deno fmt --check
      - name: check
        run: |
          deno task check
      - name: test
        run: |
          deno task test
      - name: cheap integration test
        run: |
          deno task run
  # run tests on windows because that allows us testing path.SEP related issues in integraiton tests
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@main
        with:
          deno-version: "~1.37"
      - uses: actions/cache@v3
        with:
          path: ~/.cache/deno        # see https://deno.land/manual/linking_to_external_code
          key: ${{ runner.os }}-deno # it seems there's no particular cache keying required
          restore-keys: |
            ${{ runner.os }}-deno
      - name: deno info
        run: |
          deno --version
          deno info
      - name: test
        run: |
          deno task test