name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:

jobs:
  fmt-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: deno-fmt
        id: fmt
        uses: denoland/setup-deno@main
        with:
          deno-version: "~1.34"
      - run: |
          deno fmt --check

  linting-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check-linting
        id: lint
        uses: denoland/setup-deno@main
        with:
          deno-version: "~1.34"
      - run: |
          deno lint

  build:
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@main
        with:
          deno-version: "~1.34"
      - uses: actions/cache@v3
        with:
          path: ~/.cache/deno        # see https://deno.land/manual/linking_to_external_code
          key: ${{ runner.os }}-deno # it seems there's no particular cache keying required
          restore-keys: |
            ${{ runner.os }}-deno
      - run: |
          deno --version
          deno info
          ./build.sh

      - name: Archive production artifacts
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v3
        with:
          name: collie
          path: |
            bin/**/collie-*
