name: e2e
on:
  # run after the "release" workflow https://stackoverflow.com/a/64733705/125407
  # as we need to wait for the assets to be available
  workflow_run:
    workflows: ["release"]
    branches: [main]
    types: 
      - completed

# TODO: replace "main" with "main" before merging to main branch!

jobs:
  # this test is super basic and just checks whether collie blows up
  e2e-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        uses: crazy-max/ghaction-chocolatey@v3
        # note: all other dependencies are installed in the image already
        with:
          args: install --force terraform terragrunt terraform-docs
      - name: install collie
        shell: pwsh
        env: 
          COLLIE_VERSION: ${{ github.event.release.tag_name }}
        run: |
          irm https://raw.githubusercontent.com/meshcloud/collie-cli/main/install.ps1 | iex
          
          # github doesn't allow adding to PATH any other way, see https://stackoverflow.com/a/71579543/125407
          Add-Content $env:GITHUB_PATH "C:\Users\runneradmin\collie-cli"
      - name: collie info
        shell: pwsh
        run: |
          collie info
      - name: test
        shell: pwsh
        run: .\test\e2e.ps1
  e2e-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies 
        # note: we forego default.nix and to be as close to a realistic user experience as possible
        # all the other dependencies are already present on the runner images, so we use those
        # and just install the missing ones via nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: rrbutani/use-nix-shell-action@v1
        with:
          packages: terragrunt terraform-docs
      - name: install collie
        env: 
          COLLIE_VERSION: ${{ github.event.release.tag_name }}
        run: |
          curl -sf -L https://raw.githubusercontent.com/meshcloud/collie-cli/main/install.sh | sudo bash
      - name: collie info
        run: |
          collie info
      - name: test
        run: |
          ./test/e2e.sh